name: 'toronto_housing'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'toronto_housing'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations: materialize staging as views, marts as tables
models:
  toronto_housing:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
